# This configuration was used Ebert to review the pragmaticivan/gandalf repository
# on 67e2ac7cf851cec0b4ad112771d306a54dc778bf.
# You can make this the default configuration for future reviews by moving this
# file to your repository as `.ebert.yml` and pushing it to GitHub, and tweak
# it as you wish - To know more on how to change this file to better review your
# repository you can go to https://docs.ebertapp.io/configuration and see the configuration
# details.
---
styleguide: plataformatec/linters
engines:
  credo:
    enabled: true
  fixme:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
- config
- test

