version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix test
